### ISSUE TITLE
Handling of outgoing and incoming arcs

### ISSUE THREAD

**Issue by atmani-massinissa** [malllabiisc/WordGCN#6]
Hello,
Thank you for your paper, as well as releasing the code.

 My question is about Processing of edges in the GCN, the original paper differentiated incomings and outgoing arcs by modeling two matrices, each one for each direction. They do so to avoid overparametrize the model (when adding reversed edges), also I saw that you compute the self loop vector, but you did not include it in the update formulae. 

Could you tell me if I misunderstood the code.

Thank you

Kindly regards

**Comment by svjan5** [comment]
Hi @atmani-massinissa,
Yes, the prior works such as [Marcheggiani et al. (2017)](https://www.aclweb.org/anthology/D17-1159/) ignore edge labels and consider only the direction of edges for avoiding overparameterization. However, in our work, since the corpus is sufficiently large we do not follow them. We utilize all edge label information and also consider their direction. We do not include self-loops in SynGCN as this helps to avoid overfitting to the initial embeddings, which is undesirable in the case of SynGCN as it uses random initialization. 

Thanks

**Comment by atmani-massinissa** [comment]
I understand, 

Thank you for your clarification.

Cordially
